### ISSUE TITLE
:id and :uid are nil on CLJS?? 

### ISSUE THREAD

**Issue by johanatan** [taoensso/telemere#18]
.

**Comment by ptaoussanis** [comment]
@johanatan Hi Jonathan - can you please show an example of your signal creator call?

**Comment by johanatan** [comment]
`(tel/log! {:level :error :error ex} "Insuffient data")`

**Comment by ptaoussanis** [comment]
Great, thanks 👍

So that call will intentionally generate signals **without** an id or uid.

To include an id, you'll need to specify one - e.g.:

```clojure
(tel/with-signal
  (tel/log! {:level :error, :error ex, :id ::my-id} "Insuffient data")) ; => {:id ::my-id ...}
```

Likewise, signals don't get a `:uid` by default unless they're tracing (see `trace!` or `spy!`):

```clojure
(with-signal (trace! {:level :error} (do "my form"))) ; => {:uid "gDDvd6QYqjwPTwm4Zj__E" ...}, etc.
```

It _should_ actually be possible to also do this to force an auto uid even when not tracing-

```clojure
(tel/log! {:level :error, :error ex, :id ::my-id, :uid :auto})
```

But I can see that's currently not working. Will get it fixed in the next beta 👍 I'll also update the docs to make it clearer that uids are automatic by default only when tracing.

Does that help?

**Comment by johanatan** [comment]
Yes, thank you.
