### ISSUE TITLE
logs print in utc? any possible way to configure for local time zone? 

### ISSUE THREAD

**Issue by johanatan** [taoensso/telemere#19]
sorry if it is covered in the docs. a search for "timezone" across the project turned up nothing.

**Comment by johanatan** [comment]
this is regarding the `handler:console` default handler.

**Comment by ptaoussanis** [comment]
@johanatan Hi Jonathan, yes- timestamps are displayed in UTC by default.
Specifically `ISO8601` (`YYYY-MM-DDTHH:mm:ss.sssZ`, e.g. \"2011-12-03T10:15:130Z\").

[handler:console](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere#handler:console) timestamp formatting is controlled by the `:output-fn` option - which uses [this](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere#format-signal-fn) by default, which uses [this](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere.utils#signal-preamble-fn), which finally uses [this](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere.utils#format-inst-fn).

The indirection is a bit tedious while configuring things at first, but the approach is very flexible and fast.

Hope that helps?

**Comment by johanatan** [comment]
Ok, I'm on CLJS so Zone is not supported in that final function? Is there any way to accomplish the same on CLJS?

**Comment by ptaoussanis** [comment]
> Is there any way to accomplish the same on CLJS?

[format-inst-fn](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere.utils#format-inst-fn)'s Cljs implementation uses [toISOString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) by default (UTC), otherwise you can provider a custom [goog.i18n.DateTimeFormat](https://google.github.io/closure-library/api/goog.i18n.DateTimeFormat.html) (also UTC I _believe_), or any custom formatter.

If you need a non-UTC zone, you might need to go with a custom formatter. I believe there should be JS libs available for locale formatting, but I'm not familiar enough with this to recommend anything - sorry!

Hope that's of some help at least.

**Comment by johanatan** [comment]
Well not really. I can do the conversion myself several different ways. The part I'm confused about is the "config", the where/how do I plug in my custom code. An example or short code snippet would be great, omitting the actual conversion if you like for brevity / ease of demonstration.

**Comment by ptaoussanis** [comment]
Sure, here you go:

```clojure
(with-handler ::my-handler
  (handler:console
    {:output-fn
     (utils/format-signal-fn
       {:preamble-fn (utils/signal-preamble-fn {:format-inst-fn (fn [inst] "My fmt")})})})
  (log! "Example signal"))
```

You can replace `(fn [inst] "My fmt")` with the `js/Date` formatter of your choice.

**Comment by johanatan** [comment]
Awesome. Thank you!

**Comment by ptaoussanis** [comment]
No worries, cheers :-)

**Comment by blnote** [comment]
Hi, sry for capturing the thread! I am wondering why setting a zone offset has no effect for me. The following still returns UTC
```
(let [z-offset (-> "Europe/Berlin"
                    java.time.ZoneId/of
                    java.time.ZonedDateTime/now
                    (.getOffset))]
  ((tu/format-inst-fn {:zone z-offset}) (.toInstant (java.util.Date.))))
```
Thanks!

**Comment by ptaoussanis** [comment]
@blnote Hi Bastian, no worries!

The issue is that the default formatter is `java.time.format.DateTimeFormatter/ISO_INSTANT` which ignores the `:zone` you're providing.

Basically the following is being called:

```clojure
(.format
    (.withZone java.time.format.DateTimeFormatter/ISO_INSTANT
      (.getOffset (java.time.ZonedDateTime/now (java.time.ZoneId/of "Europe/Berlin"))))
    (.toInstant (java.util.Date.))) ; => UTC ISO timestamp
```

To get the behaviour you want, you'll need to also specify an appropriate [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html), e.g.:

```clojure
((format-inst-fn
   {:formatter (java.time.format.DateTimeFormatter/ofPattern "yyyy-MM-dd'T'HH:mm:ssXXX")
    :zone      (.getOffset (java.time.ZonedDateTime/now (java.time.ZoneId/of "Europe/Berlin")))})
 (.toInstant (java.util.Date.))) ; => "2024-10-07T18:32:58+02:00"
```

Is that helpful?

Apologies for the confusion, this is an easy thing to get tripped up on - I'll add a note to the docstring.

**Comment by ptaoussanis** [comment]
**Update**: this'll hopefully be a little clearer in the [new docstring](https://github.com/taoensso/encore/commit/2a77ea4bc3b699af78e04e56315e1921a1b0fc8b), but alternative suggestions also welcome!

**Comment by blnote** [comment]
thanks, that clears it up! I was not paying attention to  :formatter

**Comment by ptaoussanis** [comment]
You're welcome, thanks for the confirmation 👍
