### ISSUE TITLE
just a typo in the docs

### ISSUE THREAD

**Issue by blnote** [taoensso/telemere#27]
in
https://github.com/taoensso/telemere/wiki/4-Handlers#handler-specific-opts

first link points to:

https://cljdoc.org/d/com.taoensso/telemere/CONSOLE/api/taoensso.telemere#handler:console

(CONSOLE instead of CURRENT).

also to simplify a little, maybe the following sentences at the beginning of the Handler wiki page could be omitted, since the info is contained below in the create handler section

> Here's a simple handler: (fn [signal] (println signal)).
> A second 0-arg arity will be called when stopping the handler. This is handy for stateful handlers or handlers that need to release resources, e.g.:
> (fn my-handler ([] (my-stop-code)) ([signal] (println signal))

Best, Bastian

**Comment by ptaoussanis** [comment]
@blnote Hi Bastian, thanks for catching the typo!

> also to simplify a little, maybe the following sentences at the beginning of the Handler wiki page could be omitted, since the info is contained below in the create handler section

That's a very reasonable suggestion, though the current repetition is intentional. A lot of people skim documentation, and might not make it down to the "Writing handlers" section.

In this particular case the info is quite fundamental so I'd prefer to err on the side of being overly repetitive.

Hope that makes sense / seems reasonable?

Cheers! :-)
