### ISSUE TITLE
Consider allowing forms within `with-ctx` and `with-ctx+`

### ISSUE THREAD

**Issue by rschmukler** [taoensso/telemere#31]
Currently you can only use a single form inside `with-ctx` and its sibling. Generally, `with-*` forms are variadic.

ie. I would expect the following to work:
```clojure
(tel/with-ctx+ {:foo "bar"}
  (tel/log! "Something with context")
  (tel/log! "Something else with context"))
```

**Comment by ptaoussanis** [comment]
Hi Ryan-

That's a totally reasonable expectation, though the current limitation is actually intentional. I'm not generally a fan of variadic `& body` signatures, though I understand that they're very common in Clojure.

The main downside is that they completely shut the door to possible future extensions to arity, and their only upside is avoiding a `(do ...)` - which I don't believe is a big deal in practice.

I have however seen numerous cases where prematurely choosing an `& body` sig led to regret later.

Can of course always change this later if/when we're very confident that there'll be no desire to extend to other arities. But in the meantime I'd prefer to keep this door open, especially while the library is new.

Hope that makes sense?
