### ISSUE TITLE
No namespace info for tools.logging signals

### ISSUE THREAD

**Issue by AlexChalk** [taoensso/telemere#9]
Hi, thanks for all your work on this! I've tried a few different ways to limit ring.logger output like the following to errors, but none of the below filter the log entries:
```shell
2024-05-23T20:13:00.759634816Z INFO LOG me :taoensso.telemere/tools-logging - {:request-method :get, :uri "/health", :server-name "localhost", :ring.logger/type :finish, :status 200, :ring.logger/ms 50}
```
```clojure
(t/set-min-level! nil "ring.logger" :error)
(t/set-min-level! nil "ring.logger*" :error)
(t/set-min-level! nil "ring.logger.*" :error)
(t/set-min-level! nil "taoensso.telemere/tools-logging" :error)
(t/set-min-level! nil "taoensso.telemere/tools-logging*" :error)
(t/set-min-level! nil "taoensso.telemere/tools-logging.*" :error)
(t/set-min-level! nil "my.app*" :error)
```
I have this issue with other libraries too, e.g. `(t/set-min-level! nil "org.eclipse.jetty" :error)` doesn't filter jetty logs. 

`(t/set-min-level! :error)` works fine. Can you advise me on where I'm going wrong?

**Comment by ptaoussanis** [comment]
@AlexChalk Hi Alex, you're very welcome!

So your syntax for `set-min-level!` looks good, but from observing the `:taoensso.telemere/tools-logging` id - the problem is likely this:

[`tools.logging`](https://github.com/clojure/tools.logging) unfortunately doesn't capture namespace information - so the signals you're trying to filter actually have a `nil` namespace.

When you create a signal _directly with Telemere_ (i.e. with a Telemere API call in your code), it's able to capture callsite information like your namespace and line number. You can see this by checking the signal content:

```
(select-keys (t/with-signal (t/log! "My message")) [:ns :line]) => {:ns "my-namespace", :line 416})
```

So in this case we can set a minimum level with a namespace pattern and have it behave as expected:

```
(t/set-min-level! nil "my-namespace" :error)
(t/with-signal (t/log! "My message")) ; => nil (insufficient level: `:info` < `:error`)
```

The problem in your case is that your signals aren't actually being created by Telemere API calls in the Jetty code, etc. Instead, `org.eclipse.jetty` is calling the `tools.logging` API 
 - which doesn't capture namespace information in the first place. All it's capturing is the level and message, which are then [redirected](https://github.com/taoensso/telemere/blob/4d793594de029dd6d03181745656fa7fc5195836/src/taoensso/telemere/tools_logging.clj#L24) to Telemere.

So by the time Telemere knows about the logging call, all it has is the level and message. It doesn't have callsite information; not even the namespace.

Unfortunately that's one of the disadvantages of logging facades like `tools.logging` or SLF4J. They offer the flexibility to choose a backend, but the big downside is that they then force the lowest-common-denominator feature set on every backend. In this case no namespaces.

How to work around this?

Options are a little limited, since we're fundamentally constrained by what external libraries are doing (`org.eclipse.jetty` not collecting ns info, etc.).

One way _might_ be to invert your logic:

- You know that your own Telemere signals _will_ have a namespace.
- All interop signals (generated via `tools.logging` or `SLF4J`, etc.) will _not_ have a namespace. 

So you could potentially do something like this:

```
(set-min-level! :error) ; Set high default min level
(set-min-level! nil "taoensso.telemere*" :info) ; Set lower min level for your code
```

Unfortunately that'll mean effectively setting an `:error` level for ALL logs outside your application (not just from the `org.eclipse.jetty` ns). But that might be a decent-enough compromise in some cases?

Sorry about the confusion on this! Your expectation that this'd work is totally reasonable. I'll update the relevant docs to help warn about the limitations of interop, and I'll give some more thought to what else (if anything) I might be able to do from Telemere's end to make it easier to work around these limitations.

**Comment by ptaoussanis** [comment]
@AlexChalk Just pushed [beta14](https://github.com/taoensso/telemere/releases) which includes [this change](https://github.com/taoensso/telemere/commit/22c46afa04ecabb8baf395662ea54b20e6a45007) so that:

1. Logger names are now used as namespaces for SLF4J and `tools.logging` signals.
2. These now have dedicated :kind (:slf4j, :tools.logging) to make it easier to set kind-specific min levels.

Hopefully that addresses the current issue?

**Comment by AlexChalk** [comment]
@ptaoussanis yep, `(t/set-min-level! nil "ring.logger*" :error)` now works, thanks so much!

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation. And thanks again for pinging about this!
